import { MyBook } from '@/@types/book'

export const MockBook = {
  webToon: [],
  webNovel: [
    {
      id: '0',
      title: '전지적 독자 시점',
      image: '/images/profile.png',
      author: '싱숑',
      genre: '판타지',
      platforms: ['naver', 'kakao', 'ridi'],
      total: 790,
      current: 519,
      score: 9872,
      episodes: [
        { ep: 1, platform: 'naver' },
        { ep: 2, platform: 'naver' },
        { ep: 3, platform: 'naver' },
        { ep: 4, platform: 'naver' },
        { ep: 5, platform: 'naver' },
        { ep: 6, platform: 'naver' },
        { ep: 7, platform: 'naver' },
        { ep: 8, platform: 'kakao' },
        { ep: 9, platform: 'kakao' },
        { ep: 10, platform: 'kakao' },
        { ep: 11, platform: 'kakao' },
        { ep: 12, platform: 'kakao' },
        { ep: 13, platform: 'kakao' },
        { ep: 14, platform: 'naver' },
        { ep: 15, platform: 'naver' },
        { ep: 16, platform: 'naver' },
        { ep: 17, platform: 'naver' },
        { ep: 18, platform: 'naver' },
        { ep: 19, platform: 'naver' },
        { ep: 20, platform: 'naver' },
        { ep: 21, platform: 'naver' },
        { ep: 22, platform: 'naver' },
        { ep: 23, platform: 'naver' },
        { ep: 24, platform: 'naver' },
        { ep: 25, platform: 'naver' },
        { ep: 26, platform: 'naver' },
        { ep: 27, platform: 'naver' },
        { ep: 28, platform: 'naver' },
        { ep: 29, platform: 'naver' },
        { ep: 30, platform: 'naver' },
        { ep: 31, platform: 'naver' },
        { ep: 32, platform: 'naver' },
        { ep: 33, platform: 'naver' },
        { ep: 34, platform: 'naver' },
        { ep: 35, platform: 'naver' },
        { ep: 36, platform: 'naver' },
        { ep: 37, platform: 'ridi' },
        { ep: 38, platform: 'ridi' },
        { ep: 39, platform: 'ridi' },
        { ep: 40, platform: 'ridi' },
        { ep: 41, platform: 'ridi' },
        { ep: 42, platform: 'ridi' },
        { ep: 43, platform: 'ridi' },
        { ep: 44, platform: 'ridi' },
        { ep: 45, platform: 'ridi' },
        { ep: 46, platform: 'ridi' },
      ],
      isDirect: false,
    },
    {
      id: '1',
      title: '나 혼자만 레벨업',
      image: '/images/test.png',
      author: '추공',
      genre: '판타지',
      platforms: ['naver', 'kakao', 'ridi'],
      total: 271,
      current: 200,
      score: 4504,
      episodes: [
        { ep: 1, platform: 'naver' },
        { ep: 2, platform: 'naver' },
        { ep: 3, platform: 'naver' },
        { ep: 4, platform: 'naver' },
        { ep: 5, platform: 'naver' },
        { ep: 6, platform: 'naver' },
        { ep: 7, platform: 'naver' },
        { ep: 8, platform: 'kakao' },
        { ep: 9, platform: 'kakao' },
        { ep: 10, platform: 'kakao' },
        { ep: 11, platform: 'kakao' },
        { ep: 12, platform: 'kakao' },
        { ep: 13, platform: 'kakao' },
        { ep: 14, platform: 'naver' },
        { ep: 15, platform: 'naver' },
        { ep: 16, platform: 'naver' },
        { ep: 17, platform: 'naver' },
        { ep: 18, platform: 'naver' },
        { ep: 19, platform: 'naver' },
        { ep: 20, platform: 'naver' },
        { ep: 21, platform: 'naver' },
        { ep: 22, platform: 'naver' },
        { ep: 23, platform: 'naver' },
        { ep: 24, platform: 'naver' },
        { ep: 25, platform: 'naver' },
        { ep: 26, platform: 'naver' },
        { ep: 27, platform: 'naver' },
        { ep: 28, platform: 'naver' },
        { ep: 29, platform: 'naver' },
        { ep: 30, platform: 'naver' },
        { ep: 31, platform: 'naver' },
        { ep: 32, platform: 'naver' },
        { ep: 33, platform: 'naver' },
        { ep: 34, platform: 'naver' },
        { ep: 35, platform: 'naver' },
        { ep: 36, platform: 'naver' },
        { ep: 37, platform: 'ridi' },
        { ep: 38, platform: 'ridi' },
        { ep: 39, platform: 'ridi' },
        { ep: 40, platform: 'ridi' },
        { ep: 41, platform: 'ridi' },
        { ep: 42, platform: 'ridi' },
        { ep: 43, platform: 'ridi' },
        { ep: 44, platform: 'ridi' },
        { ep: 45, platform: 'ridi' },
        { ep: 46, platform: 'ridi' },
        { ep: 47, platform: 'ridi' },
        { ep: 48, platform: 'ridi' },
        { ep: 49, platform: 'ridi' },
        { ep: 50, platform: 'ridi' },
        { ep: 51, platform: 'ridi' },
        { ep: 52, platform: 'ridi' },
        { ep: 53, platform: 'ridi' },
        { ep: 54, platform: 'ridi' },
        { ep: 55, platform: 'ridi' },
        { ep: 56, platform: 'ridi' },
        { ep: 57, platform: 'ridi' },
        { ep: 58, platform: 'ridi' },
        { ep: 59, platform: 'ridi' },
        { ep: 60, platform: 'ridi' },
        { ep: 61, platform: 'ridi' },
        { ep: 62, platform: 'ridi' },
        { ep: 63, platform: 'ridi' },
        { ep: 64, platform: 'ridi' },
        { ep: 65, platform: 'ridi' },
        { ep: 66, platform: 'ridi' },
        { ep: 67, platform: 'ridi' },
        { ep: 68, platform: 'ridi' },
        { ep: 69, platform: 'ridi' },
        { ep: 70, platform: 'ridi' },
        { ep: 71, platform: 'ridi' },
        { ep: 72, platform: 'ridi' },
        { ep: 73, platform: 'ridi' },
        { ep: 74, platform: 'ridi' },
        { ep: 75, platform: 'ridi' },
        { ep: 76, platform: 'ridi' },
        { ep: 77, platform: 'ridi' },
        { ep: 78, platform: 'ridi' },
        { ep: 79, platform: 'ridi' },
        { ep: 80, platform: 'ridi' },
        { ep: 81, platform: 'ridi' },
        { ep: 82, platform: 'ridi' },
        { ep: 83, platform: 'ridi' },
        { ep: 84, platform: 'ridi' },
        { ep: 85, platform: 'ridi' },
        { ep: 86, platform: 'ridi' },
        { ep: 87, platform: 'ridi' },
        { ep: 88, platform: 'ridi' },
        { ep: 89, platform: 'ridi' },
        { ep: 90, platform: 'ridi' },
        { ep: 91, platform: 'ridi' },
        { ep: 92, platform: 'ridi' },
        { ep: 93, platform: 'ridi' },
        { ep: 94, platform: 'ridi' },
        { ep: 95, platform: 'ridi' },
        { ep: 96, platform: 'ridi' },
        { ep: 97, platform: 'ridi' },
        { ep: 98, platform: 'ridi' },
        { ep: 99, platform: 'ridi' },
        { ep: 100, platform: 'ridi' },
        { ep: 101, platform: 'ridi' },
        { ep: 102, platform: 'ridi' },
        { ep: 103, platform: 'ridi' },
        { ep: 104, platform: 'ridi' },
        { ep: 105, platform: 'ridi' },
        { ep: 106, platform: 'ridi' },
      ],
      isDirect: false,
    },
    {
      id: '2',
      title: '피오니-살인귀 대공과의 미래를 보았다',
      image: '/images/profile.png',
      author: '은려원',
      genre: '로판',
      platforms: ['kakao'],
      total: 223,
      current: 98,
      score: 3092,
      episodes: [
        { ep: 1, platform: 'naver' },
        { ep: 2, platform: 'naver' },
        { ep: 3, platform: 'naver' },
        { ep: 4, platform: 'naver' },
        { ep: 5, platform: 'naver' },
        { ep: 6, platform: 'naver' },
        { ep: 7, platform: 'naver' },
        { ep: 8, platform: 'kakao' },
        { ep: 9, platform: 'kakao' },
        { ep: 10, platform: 'kakao' },
        { ep: 11, platform: 'kakao' },
        { ep: 12, platform: 'kakao' },
        { ep: 13, platform: 'kakao' },
        { ep: 14, platform: 'naver' },
        { ep: 15, platform: 'naver' },
        { ep: 16, platform: 'naver' },
        { ep: 17, platform: 'naver' },
        { ep: 18, platform: 'naver' },
        { ep: 19, platform: 'naver' },
        { ep: 20, platform: 'naver' },
        { ep: 21, platform: 'naver' },
        { ep: 22, platform: 'naver' },
        { ep: 23, platform: 'naver' },
        { ep: 24, platform: 'naver' },
        { ep: 25, platform: 'naver' },
        { ep: 26, platform: 'naver' },
        { ep: 27, platform: 'naver' },
        { ep: 28, platform: 'naver' },
        { ep: 29, platform: 'naver' },
        { ep: 30, platform: 'naver' },
        { ep: 31, platform: 'naver' },
        { ep: 32, platform: 'naver' },
        { ep: 33, platform: 'naver' },
        { ep: 34, platform: 'naver' },
        { ep: 35, platform: 'naver' },
        { ep: 36, platform: 'naver' },
        { ep: 37, platform: 'ridi' },
        { ep: 38, platform: 'ridi' },
        { ep: 39, platform: 'ridi' },
        { ep: 40, platform: 'ridi' },
        { ep: 41, platform: 'ridi' },
        { ep: 42, platform: 'ridi' },
        { ep: 43, platform: 'ridi' },
        { ep: 44, platform: 'ridi' },
        { ep: 45, platform: 'ridi' },
        { ep: 46, platform: 'ridi' },
      ],
      isDirect: false,
    },
    {
      id: '3',
      title: '없는 작품',
      image: '',
      author: '저자',
      genre: '',
      platforms: [],
      total: 0,
      current: 0,
      score: 101,
      episodes: [],
      isDirect: true,
    },
  ] as MyBook[],
}
