import { Book, MyBook } from '@/@types/book'

export const MockBook = {
  webToon: [
    {
      id: '12',
      type: 'webToon',
      title: '전지적 독자 시점',
      image: '/images/profile.png',
      author: '싱숑',
      genre: '판타지',
      platforms: [
        { label: '네이버시리즈', value: 'naver' },
        { label: '카카오페이지', value: 'kakao' },
        { label: '리디북스', value: 'ridi' },
      ],
      score: 9872,
      total: 270,
      status: { label: '완결', value: 'complete' },
      publisher: '파피루스',
      tags: ['웹툰', '판타지', '현대판타지'],
      synopsis:
        '「패왕을 보았다」의 작가 추공. 이번에는 레이드의 진수를 보여준다!\n『나 혼자만 레벨업』\n재능 없는 만년 E급의 헌터, 성진우.\n기이한 던전에서 죽음을 목전에 두지만위기는 언제나 기회와 함께 찾아오는 법!\n[플레이어가 되실 자격을 획득하셨습니다.]\n“플레이어? 내가 레벨업을 할 수 있다고?”\n전 세계 헌터 중 유일무이, 전무후무시스템과 레벨업 능력을 각성한 진우.\n세상을 향해 자유를 선포한다!',
    },
    {
      id: '13',
      type: 'webToon',
      title: '나 혼자만 레벨업',
      image: '/images/profile.png',
      author: '추공',
      genre: '판타지',
      platforms: [
        { label: '네이버시리즈', value: 'naver' },
        { label: '카카오페이지', value: 'kakao' },
        { label: '리디북스', value: 'ridi' },
      ],
      score: 4504,
      total: 270,
      status: { label: '완결', value: 'complete' },
      publisher: '파피루스',
      tags: ['웹툰', '판타지', '현대판타지'],
      synopsis:
        '「패왕을 보았다」의 작가 추공. 이번에는 레이드의 진수를 보여준다!\n『나 혼자만 레벨업』\n재능 없는 만년 E급의 헌터, 성진우.\n기이한 던전에서 죽음을 목전에 두지만위기는 언제나 기회와 함께 찾아오는 법!\n[플레이어가 되실 자격을 획득하셨습니다.]\n“플레이어? 내가 레벨업을 할 수 있다고?”\n전 세계 헌터 중 유일무이, 전무후무시스템과 레벨업 능력을 각성한 진우.\n세상을 향해 자유를 선포한다!',
    },
    {
      id: '14',
      type: 'webToon',
      title: '피오니-살인귀 대공과의 미래를 보았다',
      image: '/images/profile.png',
      author: '은려원',
      genre: '로판',
      platforms: [{ label: '카카오페이지', value: 'kakao' }],
      score: 3092,
      total: 270,
      status: { label: '완결', value: 'complete' },
      publisher: '파피루스',
      tags: ['웹툰', '판타지', '현대판타지'],
      synopsis:
        '「패왕을 보았다」의 작가 추공. 이번에는 레이드의 진수를 보여준다!\n『나 혼자만 레벨업』\n재능 없는 만년 E급의 헌터, 성진우.\n기이한 던전에서 죽음을 목전에 두지만위기는 언제나 기회와 함께 찾아오는 법!\n[플레이어가 되실 자격을 획득하셨습니다.]\n“플레이어? 내가 레벨업을 할 수 있다고?”\n전 세계 헌터 중 유일무이, 전무후무시스템과 레벨업 능력을 각성한 진우.\n세상을 향해 자유를 선포한다!',
    },
    {
      id: '15',
      type: 'webToon',
      title: '길사',
      image: '/images/profile.png',
      author: 'carbo(도효원)',
      genre: '로맨스',
      platforms: [{ label: '리디북스', value: 'ridi' }],
      score: 935,
      total: 270,
      status: { label: '완결', value: 'complete' },
      publisher: '파피루스',
      tags: ['웹툰', '판타지', '현대판타지'],
      synopsis:
        '「패왕을 보았다」의 작가 추공. 이번에는 레이드의 진수를 보여준다!\n『나 혼자만 레벨업』\n재능 없는 만년 E급의 헌터, 성진우.\n기이한 던전에서 죽음을 목전에 두지만위기는 언제나 기회와 함께 찾아오는 법!\n[플레이어가 되실 자격을 획득하셨습니다.]\n“플레이어? 내가 레벨업을 할 수 있다고?”\n전 세계 헌터 중 유일무이, 전무후무시스템과 레벨업 능력을 각성한 진우.\n세상을 향해 자유를 선포한다!',
    },
    {
      id: '16',
      type: 'webToon',
      title: '전지적 독자 시점',
      image: '/images/profile.png',
      author: '싱숑',
      genre: '판타지',
      platforms: [
        { label: '네이버시리즈', value: 'naver' },
        { label: '카카오페이지', value: 'kakao' },
        { label: '리디북스', value: 'ridi' },
      ],
      score: 9872,
      total: 270,
      status: { label: '완결', value: 'complete' },
      publisher: '파피루스',
      tags: ['웹툰', '판타지', '현대판타지'],
      synopsis:
        '「패왕을 보았다」의 작가 추공. 이번에는 레이드의 진수를 보여준다!\n『나 혼자만 레벨업』\n재능 없는 만년 E급의 헌터, 성진우.\n기이한 던전에서 죽음을 목전에 두지만위기는 언제나 기회와 함께 찾아오는 법!\n[플레이어가 되실 자격을 획득하셨습니다.]\n“플레이어? 내가 레벨업을 할 수 있다고?”\n전 세계 헌터 중 유일무이, 전무후무시스템과 레벨업 능력을 각성한 진우.\n세상을 향해 자유를 선포한다!',
    },
    {
      id: '17',
      type: 'webToon',
      title: '나 혼자만 레벨업',
      image: '/images/profile.png',
      author: '추공',
      genre: '판타지',
      platforms: [
        { label: '네이버시리즈', value: 'naver' },
        { label: '카카오페이지', value: 'kakao' },
        { label: '리디북스', value: 'ridi' },
      ],
      score: 4504,
      total: 270,
      status: { label: '완결', value: 'complete' },
      publisher: '파피루스',
      tags: ['웹툰', '판타지', '현대판타지'],
      synopsis:
        '「패왕을 보았다」의 작가 추공. 이번에는 레이드의 진수를 보여준다!\n『나 혼자만 레벨업』\n재능 없는 만년 E급의 헌터, 성진우.\n기이한 던전에서 죽음을 목전에 두지만위기는 언제나 기회와 함께 찾아오는 법!\n[플레이어가 되실 자격을 획득하셨습니다.]\n“플레이어? 내가 레벨업을 할 수 있다고?”\n전 세계 헌터 중 유일무이, 전무후무시스템과 레벨업 능력을 각성한 진우.\n세상을 향해 자유를 선포한다!',
    },
    {
      id: '18',
      type: 'webToon',
      title: '피오니-살인귀 대공과의 미래를 보았다',
      image: '/images/profile.png',
      author: '은려원',
      genre: '로판',
      platforms: [{ label: '카카오페이지', value: 'kakao' }],
      score: 3092,
      total: 270,
      status: { label: '완결', value: 'complete' },
      publisher: '파피루스',
      tags: ['웹툰', '판타지', '현대판타지'],
      synopsis:
        '「패왕을 보았다」의 작가 추공. 이번에는 레이드의 진수를 보여준다!\n『나 혼자만 레벨업』\n재능 없는 만년 E급의 헌터, 성진우.\n기이한 던전에서 죽음을 목전에 두지만위기는 언제나 기회와 함께 찾아오는 법!\n[플레이어가 되실 자격을 획득하셨습니다.]\n“플레이어? 내가 레벨업을 할 수 있다고?”\n전 세계 헌터 중 유일무이, 전무후무시스템과 레벨업 능력을 각성한 진우.\n세상을 향해 자유를 선포한다!',
    },
    {
      id: '19',
      type: 'webToon',
      title: '길사',
      image: '/images/profile.png',
      author: 'carbo(도효원)',
      genre: '로맨스',
      platforms: [{ label: '리디북스', value: 'ridi' }],
      score: 935,
      total: 270,
      status: { label: '완결', value: 'complete' },
      publisher: '파피루스',
      tags: ['웹툰', '판타지', '현대판타지'],
      synopsis:
        '「패왕을 보았다」의 작가 추공. 이번에는 레이드의 진수를 보여준다!\n『나 혼자만 레벨업』\n재능 없는 만년 E급의 헌터, 성진우.\n기이한 던전에서 죽음을 목전에 두지만위기는 언제나 기회와 함께 찾아오는 법!\n[플레이어가 되실 자격을 획득하셨습니다.]\n“플레이어? 내가 레벨업을 할 수 있다고?”\n전 세계 헌터 중 유일무이, 전무후무시스템과 레벨업 능력을 각성한 진우.\n세상을 향해 자유를 선포한다!',
    },
    {
      id: '20',
      type: 'webToon',
      title: '전지적 독자 시점',
      image: '/images/profile.png',
      author: '싱숑',
      genre: '판타지',
      platforms: [
        { label: '네이버시리즈', value: 'naver' },
        { label: '카카오페이지', value: 'kakao' },
        { label: '리디북스', value: 'ridi' },
      ],
      score: 9872,
      total: 270,
      status: { label: '완결', value: 'complete' },
      publisher: '파피루스',
      tags: ['웹툰', '판타지', '현대판타지'],
      synopsis:
        '「패왕을 보았다」의 작가 추공. 이번에는 레이드의 진수를 보여준다!\n『나 혼자만 레벨업』\n재능 없는 만년 E급의 헌터, 성진우.\n기이한 던전에서 죽음을 목전에 두지만위기는 언제나 기회와 함께 찾아오는 법!\n[플레이어가 되실 자격을 획득하셨습니다.]\n“플레이어? 내가 레벨업을 할 수 있다고?”\n전 세계 헌터 중 유일무이, 전무후무시스템과 레벨업 능력을 각성한 진우.\n세상을 향해 자유를 선포한다!',
    },
    {
      id: '21',
      type: 'webToon',
      title: '나 혼자만 레벨업',
      image: '/images/profile.png',
      author: '추공',
      genre: '판타지',
      platforms: [
        { label: '네이버시리즈', value: 'naver' },
        { label: '카카오페이지', value: 'kakao' },
        { label: '리디북스', value: 'ridi' },
      ],
      score: 4504,
      total: 270,
      status: { label: '완결', value: 'complete' },
      publisher: '파피루스',
      tags: ['웹툰', '판타지', '현대판타지'],
      synopsis:
        '「패왕을 보았다」의 작가 추공. 이번에는 레이드의 진수를 보여준다!\n『나 혼자만 레벨업』\n재능 없는 만년 E급의 헌터, 성진우.\n기이한 던전에서 죽음을 목전에 두지만위기는 언제나 기회와 함께 찾아오는 법!\n[플레이어가 되실 자격을 획득하셨습니다.]\n“플레이어? 내가 레벨업을 할 수 있다고?”\n전 세계 헌터 중 유일무이, 전무후무시스템과 레벨업 능력을 각성한 진우.\n세상을 향해 자유를 선포한다!',
    },
    {
      id: '22',
      type: 'webToon',
      title: '피오니-살인귀 대공과의 미래를 보았다',
      image: '/images/profile.png',
      author: '은려원',
      genre: '로판',
      platforms: [{ label: '카카오페이지', value: 'kakao' }],
      score: 3092,
      total: 270,
      status: { label: '완결', value: 'complete' },
      publisher: '파피루스',
      tags: ['웹툰', '판타지', '현대판타지'],
      synopsis:
        '「패왕을 보았다」의 작가 추공. 이번에는 레이드의 진수를 보여준다!\n『나 혼자만 레벨업』\n재능 없는 만년 E급의 헌터, 성진우.\n기이한 던전에서 죽음을 목전에 두지만위기는 언제나 기회와 함께 찾아오는 법!\n[플레이어가 되실 자격을 획득하셨습니다.]\n“플레이어? 내가 레벨업을 할 수 있다고?”\n전 세계 헌터 중 유일무이, 전무후무시스템과 레벨업 능력을 각성한 진우.\n세상을 향해 자유를 선포한다!',
    },
    {
      id: '23',
      type: 'webToon',
      title: '길사',
      image: '/images/profile.png',
      author: 'carbo(도효원)',
      genre: '로맨스',
      platforms: [{ label: '리디북스', value: 'ridi' }],
      score: 935,
      total: 270,
      status: { label: '완결', value: 'complete' },
      publisher: '파피루스',
      tags: ['웹툰', '판타지', '현대판타지'],
      synopsis:
        '「패왕을 보았다」의 작가 추공. 이번에는 레이드의 진수를 보여준다!\n『나 혼자만 레벨업』\n재능 없는 만년 E급의 헌터, 성진우.\n기이한 던전에서 죽음을 목전에 두지만위기는 언제나 기회와 함께 찾아오는 법!\n[플레이어가 되실 자격을 획득하셨습니다.]\n“플레이어? 내가 레벨업을 할 수 있다고?”\n전 세계 헌터 중 유일무이, 전무후무시스템과 레벨업 능력을 각성한 진우.\n세상을 향해 자유를 선포한다!',
    },
  ],
  webNovel: [
    {
      id: '0',
      type: 'webNovel',
      title: '전지적 독자 시점',
      image: '/images/test.png',
      author: '싱숑',
      genre: '판타지',
      platforms: [
        { label: '네이버시리즈', value: 'naver' },
        { label: '카카오페이지', value: 'kakao' },
        { label: '리디북스', value: 'ridi' },
      ],
      score: 9872,
      total: 270,
      status: { label: '완결', value: 'complete' },
      publisher: '파피루스',
      tags: ['웹소설', '판타지', '현대판타지'],
      synopsis:
        '「패왕을 보았다」의 작가 추공. 이번에는 레이드의 진수를 보여준다!\n『나 혼자만 레벨업』\n재능 없는 만년 E급의 헌터, 성진우.\n기이한 던전에서 죽음을 목전에 두지만위기는 언제나 기회와 함께 찾아오는 법!\n[플레이어가 되실 자격을 획득하셨습니다.]\n“플레이어? 내가 레벨업을 할 수 있다고?”\n전 세계 헌터 중 유일무이, 전무후무시스템과 레벨업 능력을 각성한 진우.\n세상을 향해 자유를 선포한다!',
    },
    {
      id: '1',
      type: 'webNovel',
      title: '나 혼자만 레벨업',
      image: '/images/test.png',
      author: '추공',
      genre: '판타지',
      platforms: [
        { label: '네이버시리즈', value: 'naver' },
        { label: '카카오페이지', value: 'kakao' },
        { label: '리디북스', value: 'ridi' },
      ],
      score: 4504,
      total: 270,
      status: { label: '완결', value: 'complete' },
      publisher: '파피루스',
      tags: ['웹소설', '판타지', '현대판타지'],
      synopsis:
        '「패왕을 보았다」의 작가 추공. 이번에는 레이드의 진수를 보여준다!\n『나 혼자만 레벨업』\n재능 없는 만년 E급의 헌터, 성진우.\n기이한 던전에서 죽음을 목전에 두지만위기는 언제나 기회와 함께 찾아오는 법!\n[플레이어가 되실 자격을 획득하셨습니다.]\n“플레이어? 내가 레벨업을 할 수 있다고?”\n전 세계 헌터 중 유일무이, 전무후무시스템과 레벨업 능력을 각성한 진우.\n세상을 향해 자유를 선포한다!',
    },
    {
      id: '2',
      type: 'webNovel',
      title: '피오니-살인귀 대공과의 미래를 보았다',
      image: '/images/test.png',
      author: '은려원',
      genre: '로판',
      platforms: [{ label: '카카오페이지', value: 'kakao' }],
      score: 3092,
      total: 270,
      status: { label: '완결', value: 'complete' },
      publisher: '파피루스',
      tags: ['웹소설', '판타지', '현대판타지'],
      synopsis:
        '「패왕을 보았다」의 작가 추공. 이번에는 레이드의 진수를 보여준다!\n『나 혼자만 레벨업』\n재능 없는 만년 E급의 헌터, 성진우.\n기이한 던전에서 죽음을 목전에 두지만위기는 언제나 기회와 함께 찾아오는 법!\n[플레이어가 되실 자격을 획득하셨습니다.]\n“플레이어? 내가 레벨업을 할 수 있다고?”\n전 세계 헌터 중 유일무이, 전무후무시스템과 레벨업 능력을 각성한 진우.\n세상을 향해 자유를 선포한다!',
    },
    {
      id: '3',
      type: 'webNovel',
      title: '길사',
      image: '/images/test.png',
      author: 'carbo(도효원)',
      genre: '로맨스',
      platforms: [{ label: '리디북스', value: 'ridi' }],
      score: 935,
      total: 270,
      status: { label: '완결', value: 'complete' },
      publisher: '파피루스',
      tags: ['웹소설', '판타지', '현대판타지'],
      synopsis:
        '「패왕을 보았다」의 작가 추공. 이번에는 레이드의 진수를 보여준다!\n『나 혼자만 레벨업』\n재능 없는 만년 E급의 헌터, 성진우.\n기이한 던전에서 죽음을 목전에 두지만위기는 언제나 기회와 함께 찾아오는 법!\n[플레이어가 되실 자격을 획득하셨습니다.]\n“플레이어? 내가 레벨업을 할 수 있다고?”\n전 세계 헌터 중 유일무이, 전무후무시스템과 레벨업 능력을 각성한 진우.\n세상을 향해 자유를 선포한다!',
    },
    {
      id: '4',
      type: 'webNovel',
      title: '전지적 독자 시점',
      image: '/images/test.png',
      author: '싱숑',
      genre: '판타지',
      platforms: [
        { label: '네이버시리즈', value: 'naver' },
        { label: '카카오페이지', value: 'kakao' },
        { label: '리디북스', value: 'ridi' },
      ],
      score: 9872,
      total: 270,
      status: { label: '완결', value: 'complete' },
      publisher: '파피루스',
      tags: ['웹소설', '판타지', '현대판타지'],
      synopsis:
        '「패왕을 보았다」의 작가 추공. 이번에는 레이드의 진수를 보여준다!\n『나 혼자만 레벨업』\n재능 없는 만년 E급의 헌터, 성진우.\n기이한 던전에서 죽음을 목전에 두지만위기는 언제나 기회와 함께 찾아오는 법!\n[플레이어가 되실 자격을 획득하셨습니다.]\n“플레이어? 내가 레벨업을 할 수 있다고?”\n전 세계 헌터 중 유일무이, 전무후무시스템과 레벨업 능력을 각성한 진우.\n세상을 향해 자유를 선포한다!',
    },
    {
      id: '5',
      type: 'webNovel',
      title: '나 혼자만 레벨업',
      image: '/images/test.png',
      author: '추공',
      genre: '판타지',
      platforms: [
        { label: '네이버시리즈', value: 'naver' },
        { label: '카카오페이지', value: 'kakao' },
        { label: '리디북스', value: 'ridi' },
      ],
      score: 4504,
      total: 270,
      status: { label: '완결', value: 'complete' },
      publisher: '파피루스',
      tags: ['웹소설', '판타지', '현대판타지'],
      synopsis:
        '「패왕을 보았다」의 작가 추공. 이번에는 레이드의 진수를 보여준다!\n『나 혼자만 레벨업』\n재능 없는 만년 E급의 헌터, 성진우.\n기이한 던전에서 죽음을 목전에 두지만위기는 언제나 기회와 함께 찾아오는 법!\n[플레이어가 되실 자격을 획득하셨습니다.]\n“플레이어? 내가 레벨업을 할 수 있다고?”\n전 세계 헌터 중 유일무이, 전무후무시스템과 레벨업 능력을 각성한 진우.\n세상을 향해 자유를 선포한다!',
    },
    {
      id: '6',
      type: 'webNovel',
      title: '피오니-살인귀 대공과의 미래를 보았다',
      image: '/images/test.png',
      author: '은려원',
      genre: '로판',
      platforms: [{ label: '카카오페이지', value: 'kakao' }],
      score: 3092,
      total: 270,
      status: { label: '완결', value: 'complete' },
      publisher: '파피루스',
      tags: ['웹소설', '판타지', '현대판타지'],
      synopsis:
        '「패왕을 보았다」의 작가 추공. 이번에는 레이드의 진수를 보여준다!\n『나 혼자만 레벨업』\n재능 없는 만년 E급의 헌터, 성진우.\n기이한 던전에서 죽음을 목전에 두지만위기는 언제나 기회와 함께 찾아오는 법!\n[플레이어가 되실 자격을 획득하셨습니다.]\n“플레이어? 내가 레벨업을 할 수 있다고?”\n전 세계 헌터 중 유일무이, 전무후무시스템과 레벨업 능력을 각성한 진우.\n세상을 향해 자유를 선포한다!',
    },
    {
      id: '7',
      type: 'webNovel',
      title: '길사',
      image: '/images/test.png',
      author: 'carbo(도효원)',
      genre: '로맨스',
      platforms: [{ label: '리디북스', value: 'ridi' }],
      score: 935,
      total: 270,
      status: { label: '완결', value: 'complete' },
      publisher: '파피루스',
      tags: ['웹소설', '판타지', '현대판타지'],
      synopsis:
        '「패왕을 보았다」의 작가 추공. 이번에는 레이드의 진수를 보여준다!\n『나 혼자만 레벨업』\n재능 없는 만년 E급의 헌터, 성진우.\n기이한 던전에서 죽음을 목전에 두지만위기는 언제나 기회와 함께 찾아오는 법!\n[플레이어가 되실 자격을 획득하셨습니다.]\n“플레이어? 내가 레벨업을 할 수 있다고?”\n전 세계 헌터 중 유일무이, 전무후무시스템과 레벨업 능력을 각성한 진우.\n세상을 향해 자유를 선포한다!',
    },
    {
      id: '8',
      type: 'webNovel',
      title: '전지적 독자 시점',
      image: '/images/test.png',
      author: '싱숑',
      genre: '판타지',
      platforms: [
        { label: '네이버시리즈', value: 'naver' },
        { label: '카카오페이지', value: 'kakao' },
        { label: '리디북스', value: 'ridi' },
      ],
      score: 9872,
      total: 270,
      status: { label: '완결', value: 'complete' },
      publisher: '파피루스',
      tags: ['웹소설', '판타지', '현대판타지'],
      synopsis:
        '「패왕을 보았다」의 작가 추공. 이번에는 레이드의 진수를 보여준다!\n『나 혼자만 레벨업』\n재능 없는 만년 E급의 헌터, 성진우.\n기이한 던전에서 죽음을 목전에 두지만위기는 언제나 기회와 함께 찾아오는 법!\n[플레이어가 되실 자격을 획득하셨습니다.]\n“플레이어? 내가 레벨업을 할 수 있다고?”\n전 세계 헌터 중 유일무이, 전무후무시스템과 레벨업 능력을 각성한 진우.\n세상을 향해 자유를 선포한다!',
    },
    {
      id: '9',
      type: 'webNovel',
      title: '나 혼자만 레벨업',
      image: '/images/test.png',
      author: '추공',
      genre: '판타지',
      platforms: [
        { label: '네이버시리즈', value: 'naver' },
        { label: '카카오페이지', value: 'kakao' },
        { label: '리디북스', value: 'ridi' },
      ],
      score: 4504,
      total: 270,
      status: { label: '완결', value: 'complete' },
      publisher: '파피루스',
      tags: ['웹소설', '판타지', '현대판타지'],
      synopsis:
        '「패왕을 보았다」의 작가 추공. 이번에는 레이드의 진수를 보여준다!\n『나 혼자만 레벨업』\n재능 없는 만년 E급의 헌터, 성진우.\n기이한 던전에서 죽음을 목전에 두지만위기는 언제나 기회와 함께 찾아오는 법!\n[플레이어가 되실 자격을 획득하셨습니다.]\n“플레이어? 내가 레벨업을 할 수 있다고?”\n전 세계 헌터 중 유일무이, 전무후무시스템과 레벨업 능력을 각성한 진우.\n세상을 향해 자유를 선포한다!',
    },
    {
      id: '10',
      type: 'webNovel',
      title: '피오니-살인귀 대공과의 미래를 보았다',
      image: '/images/test.png',
      author: '은려원',
      genre: '로판',
      platforms: [{ label: '카카오페이지', value: 'kakao' }],
      score: 3092,
      total: 270,
      status: { label: '완결', value: 'complete' },
      publisher: '파피루스',
      tags: ['웹소설', '판타지', '현대판타지'],
      synopsis:
        '「패왕을 보았다」의 작가 추공. 이번에는 레이드의 진수를 보여준다!\n『나 혼자만 레벨업』\n재능 없는 만년 E급의 헌터, 성진우.\n기이한 던전에서 죽음을 목전에 두지만위기는 언제나 기회와 함께 찾아오는 법!\n[플레이어가 되실 자격을 획득하셨습니다.]\n“플레이어? 내가 레벨업을 할 수 있다고?”\n전 세계 헌터 중 유일무이, 전무후무시스템과 레벨업 능력을 각성한 진우.\n세상을 향해 자유를 선포한다!',
    },
    {
      id: '11',
      type: 'webNovel',
      title: '길사',
      image: '/images/test.png',
      author: 'carbo(도효원)',
      genre: '로맨스',
      platforms: [{ label: '리디북스', value: 'ridi' }],
      score: 935,
      total: 270,
      status: { label: '완결', value: 'complete' },
      publisher: '파피루스',
      tags: ['웹소설', '판타지', '현대판타지'],
      synopsis:
        '「패왕을 보았다」의 작가 추공. 이번에는 레이드의 진수를 보여준다!\n『나 혼자만 레벨업』\n재능 없는 만년 E급의 헌터, 성진우.\n기이한 던전에서 죽음을 목전에 두지만위기는 언제나 기회와 함께 찾아오는 법!\n[플레이어가 되실 자격을 획득하셨습니다.]\n“플레이어? 내가 레벨업을 할 수 있다고?”\n전 세계 헌터 중 유일무이, 전무후무시스템과 레벨업 능력을 각성한 진우.\n세상을 향해 자유를 선포한다!',
    },
  ],
} as { [key: string]: Book[] }

export const MockMyBook = {
  webToon: [],
  webNovel: [
    {
      id: '0',
      title: '전지적 독자 시점',
      image: '/images/profile.png',
      author: '싱숑',
      genre: '판타지',
      platforms: [
        { label: '네이버시리즈', value: 'naver' },
        { label: '카카오페이지', value: 'kakao' },
        { label: '리디북스', value: 'ridi' },
      ],
      total: 790,
      current: 519,
      score: 9872,
      status: { label: '연재중', value: 'in series' },
      episodes: [
        { ep: 1, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 2, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 3, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 4, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 5, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 6, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 7, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 8, platform: { label: '카카오페이지', value: 'kakao' } },
        { ep: 9, platform: { label: '카카오페이지', value: 'kakao' } },
        { ep: 10, platform: { label: '카카오페이지', value: 'kakao' } },
        { ep: 11, platform: { label: '카카오페이지', value: 'kakao' } },
        { ep: 12, platform: { label: '카카오페이지', value: 'kakao' } },
        { ep: 13, platform: { label: '카카오페이지', value: 'kakao' } },
        { ep: 14, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 15, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 16, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 17, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 18, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 19, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 20, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 21, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 22, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 23, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 24, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 25, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 26, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 27, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 28, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 29, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 30, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 31, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 32, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 33, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 34, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 35, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 36, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 37, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 38, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 39, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 40, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 41, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 42, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 43, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 44, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 45, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 46, platform: { label: '리디북스', value: 'ridi' } },
      ],
      isDirect: false,
    },
    {
      id: '1',
      title: '나 혼자만 레벨업',
      image: '/images/test.png',
      author: '추공',
      genre: '판타지',
      platforms: [
        { label: '네이버시리즈', value: 'naver' },
        { label: '카카오페이지', value: 'kakao' },
        { label: '리디북스', value: 'ridi' },
      ],
      total: 271,
      current: 200,
      score: 4504,
      status: { label: '완결', value: 'complete' },
      episodes: [
        { ep: 1, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 2, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 3, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 4, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 5, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 6, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 7, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 8, platform: { label: '카카오페이지', value: 'kakao' } },
        { ep: 9, platform: { label: '카카오페이지', value: 'kakao' } },
        { ep: 10, platform: { label: '카카오페이지', value: 'kakao' } },
        { ep: 11, platform: { label: '카카오페이지', value: 'kakao' } },
        { ep: 12, platform: { label: '카카오페이지', value: 'kakao' } },
        { ep: 13, platform: { label: '카카오페이지', value: 'kakao' } },
        { ep: 14, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 15, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 16, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 17, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 18, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 19, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 20, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 21, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 22, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 23, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 24, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 25, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 26, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 27, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 28, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 29, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 30, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 31, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 32, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 33, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 34, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 35, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 36, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 37, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 38, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 39, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 40, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 41, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 42, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 43, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 44, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 45, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 46, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 47, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 48, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 49, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 50, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 51, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 52, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 53, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 54, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 55, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 56, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 57, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 58, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 59, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 60, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 61, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 62, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 63, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 64, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 65, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 66, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 67, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 68, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 69, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 70, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 71, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 72, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 73, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 74, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 75, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 76, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 77, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 78, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 79, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 80, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 81, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 82, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 83, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 84, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 85, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 86, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 87, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 88, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 89, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 90, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 91, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 92, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 93, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 94, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 95, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 96, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 97, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 98, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 99, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 100, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 101, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 102, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 103, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 104, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 105, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 106, platform: { label: '리디북스', value: 'ridi' } },
      ],
      isDirect: false,
    },
    {
      id: '2',
      title: '피오니-살인귀 대공과의 미래를 보았다',
      image: '/images/profile.png',
      author: '은려원',
      genre: '로판',
      platforms: [{ label: '카카오페이지', value: 'kakao' }],
      total: 223,
      current: 98,
      score: 3092,
      status: { label: '완결', value: 'complete' },
      episodes: [
        { ep: 1, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 2, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 3, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 4, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 5, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 6, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 7, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 8, platform: { label: '카카오페이지', value: 'kakao' } },
        { ep: 9, platform: { label: '카카오페이지', value: 'kakao' } },
        { ep: 10, platform: { label: '카카오페이지', value: 'kakao' } },
        { ep: 11, platform: { label: '카카오페이지', value: 'kakao' } },
        { ep: 12, platform: { label: '카카오페이지', value: 'kakao' } },
        { ep: 13, platform: { label: '카카오페이지', value: 'kakao' } },
        { ep: 14, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 15, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 16, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 17, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 18, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 19, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 20, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 21, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 22, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 23, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 24, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 25, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 26, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 27, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 28, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 29, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 30, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 31, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 32, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 33, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 34, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 35, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 36, platform: { label: '네이버시리즈', value: 'naver' } },
        { ep: 37, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 38, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 39, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 40, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 41, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 42, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 43, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 44, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 45, platform: { label: '리디북스', value: 'ridi' } },
        { ep: 46, platform: { label: '리디북스', value: 'ridi' } },
      ],
      isDirect: false,
    },
    {
      id: '3',
      title: '없는 작품',
      image: '',
      author: '저자',
      genre: '',
      platforms: [],
      total: 0,
      current: 0,
      score: 101,
      episodes: [],
      isDirect: true,
    },
  ] as MyBook[],
}
